version: 2

jobs:
  build:
    working_directory: ~/subtext-app
    docker:
      - image: circleci/node:10.13.0-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - subtext-app-yarn-{{ checksum "yarn.lock" }}
            - subtext-app-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn
      - run: yarn global add bower
      - run: ~/.yarn/bin/bower install

      - save_cache:
          key: subtext-app-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run tests
          command: yarn test
